env:
  FLASK_APP=server.py

dist: trusty

language: python
python: 3.6
before_install:
  - cd backend
install:
  - pip install -r requirements.txt
script:
  - test.py

addons:
  sonarcloud:
    organization: "ernoma-github"
script:
  - sonar-scanner
